### ISSUE TITLE
在更改了人生重来的talentmanager.py之后就无法载入了

### ISSUE THREAD

**Issue by anonymous-gy** [zhenxun-org/nonebot_plugins_zhenxun_bot#101]
理论上不会吧？我确定我没动int，talentmanager改动纯粹是为了增加高等天赋出现概率和天赋个数
很简单的改动，就是动了概率数组，和天赋个数判断语句（否则增加天赋个数会导致报错）

真寻对于非官方插件难道有hash检测吗？

**Comment by shinianj** [comment]
请下次提问前先把报错日志放出来
