### ISSUE TITLE
Feat: add `每日一句` plugin

### ISSUE THREAD

**Issue by xipesoy** [zhenxun-org/nonebot_plugins_zhenxun_bot#103]
## 每日一句

每日一句魔楞语录

## GitHub 地址

https://github.com/xipesoy/nonebot_plugins_zhenxun_bot/tree/index/aya-day

## 使用方法

使用方法
每日一句 参数

![)S{X6HCWXW{_4WYBOL{%G@X](https://user-images.githubusercontent.com/72912346/174517706-34a10cc3-8f30-427e-8395-e555c428d506.png)

**Comment by dishuii** [comment]
哈哈哈 别在这里理发店

**Comment by xipesoy** [comment]
> 谁也拦不住我对阿咪老婆发癫!
