### ISSUE TITLE
Atri语音包报错

### ISSUE THREAD

**Issue by a930389426** [zhenxun-org/nonebot_plugins_zhenxun_bot#108]
![1](https://user-images.githubusercontent.com/59648220/175798603-4eaf2422-96b2-48ab-9580-993ea3831d69.png)
![2](https://user-images.githubusercontent.com/59648220/175798608-3223fe92-77de-4490-86ae-3e9e5e7d224b.png)

**Comment by mzmyyds** [comment]
安装ffmpeg
https://docs.go-cqhttp.org/guide/quick_start.html#%E6%9B%B4%E6%96%B0

**Comment by a930389426** [comment]
> 安装ffmpeg https://docs.go-cqhttp.org/guide/quick_start.html#%E6%9B%B4%E6%96%B0

我已经安装了ffmpeg

**Comment by a930389426** [comment]
![image](https://user-images.githubusercontent.com/59648220/185840144-b0a809ad-d1cd-4bfb-bbf9-debb0030b33e.png)

**Comment by a930389426** [comment]
> 安装ffmpeg https://docs.go-cqhttp.org/guide/quick_start.html#%E6%9B%B4%E6%96%B0

我是本来就安装了ffmpeg然后上面报错的
