### ISSUE TITLE
大佬请问playwright的超时问题

### ISSUE THREAD

**Issue by ayanami648** [zhenxun-org/nonebot_plugins_zhenxun_bot#109]
安装棋类游戏后 使用指令显示超时
![image](https://user-images.githubusercontent.com/105802556/175862403-af1ddc3e-94bc-40a8-8bba-16c4d4313204.png)

**Comment by xipesoy** [comment]
插件放在独立的文件夹load试试  我是可以正常使用的

**Comment by ayanami648** [comment]
> 插件放在独立的文件夹load试试 我是可以正常使用的

已解决 与插件冲突 卸载即可
