### ISSUE TITLE
请教一下，“表情包制作”插件中的“nonebot_plugin_imageutils”插件无法安装的问题

### ISSUE THREAD

**Issue by TwoWenV587** [zhenxun-org/nonebot_plugins_zhenxun_bot#111]
安装“表情包制作”插件后启动bot无法加载，查看错误日志发现是少了“nonebot_plugin_imageutils”这个插件
**### 错误日志**：
![QQ截图20220628132752](https://user-images.githubusercontent.com/108177273/176100228-08483ff9-4ead-4586-b832-47d54cc6ad40.png)
随后去单独安装这个插件，报错无法安装
**### 错误日志**：
![image](https://user-images.githubusercontent.com/108177273/176100585-271411af-259c-47b4-876d-7fad6765d8f0.png)
然后去检索了一些issues没有找到相关问题，去百度发现类似的问题是在pip install 后加上--user可以解决
![image](https://user-images.githubusercontent.com/108177273/176101037-9d3d4c61-23a0-4205-acb0-a69a80b8ccde.png)
但是我添加--user之后运行安装依然报错
**### 错误日志**：
![image](https://user-images.githubusercontent.com/108177273/176101235-882f1181-ffb1-428f-b30a-403989118d17.png)
再去寻找这个报错的解决办法之后就找不到了，也没有找到类似的issues
希望大佬能够帮我解答一下T T

**Comment by RShock** [comment]
(我猜是这样的，没验证
