### ISSUE TITLE
请问成分姬用到的cookie有啥格式要求吗。

### ISSUE THREAD

**Issue by LINK-URIBOH** [zhenxun-org/nonebot_plugins_zhenxun_bot#112]
如题，在控制台使用prompt("", document.cookie);获取的cookie填入configs\config.yaml后并没有显示粉丝牌。不知道是哪里出了问题

**Comment by shenghuo2** [comment]
bilibili_cookie="SESSDATA=xxx;"
只需要SESSDATA段
