### ISSUE TITLE
Feat: add `幸运球` plugin

### ISSUE THREAD

**Issue by fluorescia** [zhenxun-org/nonebot_plugins_zhenxun_bot#114]
## 插件名

幸运球

## GitHub 地址

[插件GitHub地址](https://github.com/fluoresce0/zhenxun_plugins_luckyball)

## 备注

简化版的彩票，购买号码，每日开奖。

## 下载地址（可选）

[插件的下载地址](https://github.com/fluoresce0/zhenxun_plugins_luckyball/releases/download/v0.0.1/luckyball.zip)

**Comment by RShock** [comment]
为啥__init__.py line183要catch exception呢，如果配置文件没写KJNUM_MAX的话这里的异常会被吞掉

**Comment by fluoresce0** [comment]
> 为啥__init__.py line183要catch exception呢，如果配置文件没写KJNUM_MAX的话这里的异常会被吞掉

感谢指正，这里重新调整了一下结构，另外修正了config名字的bug。不知道有没有改对。

**Comment by RShock** [comment]
我刚刚也改了config，让它和插件名字保持一致。不过依然会有帮助功能不能用的副作用，我直接重启5次让真寻把缓存清掉就好了。。

**Comment by fluoresce0** [comment]
> 我刚刚也改了config，让它和插件名字保持一致。不过依然会有帮助功能不能用的副作用，我直接重启5次让真寻把缓存清掉就好了。。
我也删掉了usage里面的变量和上面的config获取，让触发指令的时候来提示
