### ISSUE TITLE
关于超分报错（求解决）

### ISSUE THREAD

**Issue by ILYSHL** [zhenxun-org/nonebot_plugins_zhenxun_bot#118]
昨天用好好的，今天突然不能用了···
![84VK$O4D{K~6P0L9 {FUA5C](https://user-images.githubusercontent.com/42436917/179193593-684aa848-90df-40dd-8c18-365c7c811fb2.png)
此时启动未报错，运行超分报错

重新安装依赖并安装了attribute；poetry install；无果。
重新下载插件安装后报错变了
![image](https://user-images.githubusercontent.com/42436917/179194868-082156e7-bdaf-4a53-8b2f-f9810c90faef.png)

已尽力自我解决，求大佬指点。

**Comment by DuXinyu0722** [comment]
想问一下大佬解决了这个问题了吗，我的报错跟你一模一样，但我不知道怎么解决。

**Comment by ILYSHL** [comment]
没有，我回滚快照了

**Comment by ILYSHL** [comment]
> 
没有，我回滚快照了

**Comment by ILYSHL** [comment]
> 想问一下大佬解决了这个问题了吗，我的报错跟你一模一样，但我不知道怎么解决。

没有，我回滚快照了

**Comment by HuYo-OS** [comment]
已找到报错原因，只需要把182行和186行稍微改一下就可正常使用

**Comment by HuYo-OS** [comment]
> 已找到报错原因，只需要把182行和186行稍微改一下就可正常使用

```python
i.__array__()   --->   np.asarray(i)
```
```python
image.__array__()   --->  np.assarray(image)
```

**Comment by ChthollyWn** [comment]
> 

请问超分插件一般需要多少的服务器内存呢

**Comment by ILYSHL** [comment]
> > 
> 
> 请问超分插件一般需要多少的服务器内存呢

具体不知道，我服务器2H2G但是分了10G虚拟···估计怎么也得4G往上吧

**Comment by ChthollyWn** [comment]
> > > 
> > 
> > 
> > 请问超分插件一般需要多少的服务器内存呢
> 
> 具体不知道，我服务器2H2G但是分了10G虚拟···估计怎么也得4G往上吧

我的是2h4g的，分了8g的虚拟内存，这么说应该是够用的吧
