### ISSUE TITLE
Feat: add `股海风云` plugin

### ISSUE THREAD

**Issue by RShock** [zhenxun-org/nonebot_plugins_zhenxun_bot#119]
## 插件名

股海风云

## GitHub 地址

[您的插件的 GitHub 地址](https://github.com/RShock/zhenxun_plugin_stock_legend)

## 备注

适配真寻的炒股小游戏，使用真寻经济系统和真实股市数据

## 下载地址（可选）

无，更新频繁不适合release

**Comment by yajiwa** [comment]
7e85ac8
