### ISSUE TITLE
Feat: add `算卦` plugin

### ISSUE THREAD

**Issue by kuiiue** [zhenxun-org/nonebot_plugins_zhenxun_bot#131]
## 插件名

算卦

## GitHub 地址

https://github.com/kuiiue/zhenxun-plugin-suangua

## 备注

六十四卦算卦

## 下载地址（可选）

https://github.com/kuiiue/zhenxun-plugin-suangua/releases/download/v0.1/suangua.zip

**Comment by shinianj** [comment]
已添加
