### ISSUE TITLE
Feat: add `群友老婆` plugin

### ISSUE THREAD

**Issue by sophisticate9008** [zhenxun-org/nonebot_plugins_zhenxun_bot#133]
## 插件名

群老婆

## GitHub 地址

https://github.com/sophisticate9008/draw_wife

## 备注

从群友里挑选老婆
抽群老婆 我的群老婆 呼叫老婆

## 下载地址（可选）

您插件的下载地址，必须为 GitHub Release 地址

**Comment by shinianj** [comment]
nb商店已有类似插件，所以我很抱歉
