### ISSUE TITLE
Feat: add `日韩中 VITS 模型拟声 真寻适配版` plugin

### ISSUE THREAD

**Issue by ChthollyWn** [zhenxun-org/nonebot_plugins_zhenxun_bot#141]
## 插件名

VITS语音合成

## GitHub 地址

https://github.com/ChthollyWn/zhenxun_plugins_moegoe

## 备注

日韩中 VITS 模型拟声 真寻适配版

**Comment by shinianj** [comment]
兄弟，你这是在水pr啊
