### ISSUE TITLE
使用github仓库信息卡片后会导致Ai对话功能失效

### ISSUE THREAD

**Issue by Howtyee** [zhenxun-org/nonebot_plugins_zhenxun_bot#155]
使用github仓库信息卡片后会导致Ai对话功能失效，所有的对话将被github模块接管，ai不再接管，无法响应回复。

**Comment by shinianj** [comment]
请给日志截图

**Comment by Howtyee** [comment]
> 请给日志截图

插件已卸载，不方便再装上专门提取日志，我描述一下吧，在私聊或者群聊@中 普通消息原来的最后一项是会被plugin.ai接管，然后获得ai返回的答复，但是装上此插件后所有的消息除开优先度极高的重启指令等，统统会被.github接管，ai不出现在响应日志中，无法获得答复。我的真寻为最新版。

**Comment by Howtyee** [comment]
> ai插件优先级为998，github仓库卡片优先级为5，优先级问题（顺带一提，下次请提供日志截图，若再无问题，请close）

调到优先级2也不行，我在open这个issue时试过，您可以试试。

**Comment by KnightKilito** [comment]
我看到你这，把GitHub插件卸了，果然ai就可以了
