### ISSUE TITLE
Feat: add `我的世界服务器状态查询` plugin

### ISSUE THREAD

**Issue by molanp** [zhenxun-org/nonebot_plugins_zhenxun_bot#158]
插件名

我的世界服务器状态查询

GitHub 地址

[github地址](https://github.com/molanp/zhenxun_check_Minecraft) 

备注

通过套接字链接获取信息，整理格式并发送

下载地址

[下载地址](https://github.com/molanp/zhenxun_check_Minecraft/releases/latest)

**Comment by yajiwa** [comment]
下载地址里的文件结构不对，解压出来应该是chafu/xxxx.py或者zhenxun_check_Minecraft/xxx.py

**Comment by yajiwa** [comment]
下载地址目录结构修改下，参考[贡献指南](https://github.com/zhenxun-org/nonebot_plugins_zhenxun_bot/blob/index/CONTRIBUTING.md)

**Comment by yajiwa** [comment]
> 已修改

是改压缩包，看[贡献指南](https://github.com/zhenxun-org/nonebot_plugins_zhenxun_bot/blob/index/CONTRIBUTING.md)最后，参考这个[插件](https://github.com/yajiwa/zhenxun_github_sub/releases/tag/v0.5)

**Comment by molanp** [comment]
行了

**Comment by yajiwa** [comment]
> 行了

不对，你去看我给你参考的插件，解压出来看看目录结构跟你有什么不同

**Comment by molanp** [comment]
> > 行了
> 
> 不对，你去看我给你参考的插件，解压出来看看目录结构跟你有什么不同

已修改

**Comment by yajiwa** [comment]
已添加
