### ISSUE TITLE
Feat: add `《别当欧尼酱了！》漫画鉴赏` plugin

### ISSUE THREAD

**Issue by RShock** [zhenxun-org/nonebot_plugins_zhenxun_bot#162]
## 插件名

《别当欧尼酱了！》漫画鉴赏

## GitHub 地址

[您的插件的 GitHub 地址](https://github.com/RShock/zhenxun_plugin_onimai)

## 备注

在群里看《别当欧尼酱了！》漫画

## 下载地址（可选）

无

**Comment by shinianj** [comment]
已添加至读我
