### ISSUE TITLE
Feat: add `QQ权重` plugin

### ISSUE THREAD

**Issue by xiayingLIULI** [zhenxun-org/nonebot_plugins_zhenxun_bot#163]
## 插件名

QQ权重

## GitHub 地址

* [GitHub 地址](https://github.com/xiayingLIULI/zhenxun_plugin_QQweight)

## 备注

查询个人QQ号以及真寻的QQ权重分

## 下载地址（可选）

* [GitHub Release 地址](https://github.com/xiayingLIULI/zhenxun_plugin_QQweight/releases)

**Comment by yajiwa** [comment]
下载地址目录结构修改下，参考[贡献指南](https://github.com/zhenxun-org/nonebot_plugins_zhenxun_bot/blob/index/CONTRIBUTING.md)

**Comment by xiayingLIULI** [comment]
> 下载地址目录结构修改下，参考[贡献指南](https://github.com/zhenxun-org/nonebot_plugins_zhenxun_bot/blob/index/CONTRIBUTING.md)

已修改

**Comment by yajiwa** [comment]
> 
还是不对，可以参考这个[插件](https://github.com/yajiwa/zhenxun_github_sub/releases/tag/v0.5)

**Comment by yajiwa** [comment]
已添加 [0f066cc](https://github.com/zhenxun-org/nonebot_plugins_zhenxun_bot/commit/0f066ccd4fffe70a1b267f75b0020424eb18796e)
