### ISSUE TITLE
Feat: add `牛牛大作战` plugin

### ISSUE THREAD

**Issue by molanp** [zhenxun-org/nonebot_plugins_zhenxun_bot#167]
## 插件名

牛牛大作战

## GitHub 地址

[https://github.com/molanp/zhenxun_plugin_niuniu](https://github.com/molanp/zhenxun_plugin_niuniu)

## 备注

~~*男同快乐小游戏*~~

## 下载地址（可选）

[下载地址](https://ghproxy.com/github.com/molanp/zhenxun_plugin_niuniu/releases/)

**Comment by molanp** [comment]
直接提交pr算了

**Comment by 1411484730** [comment]
这插件有点太逆天了...

**Comment by yajiwa** [comment]
下载地址目录结构修改下，参考[贡献指南](https://github.com/zhenxun-org/nonebot_plugins_zhenxun_bot/blob/index/CONTRIBUTING.md)

**Comment by molanp** [comment]
已修改

**Comment by kuai364354200** [comment]
做个人hhhhhhh

**Comment by yajiwa** [comment]
已添加
