### ISSUE TITLE
github订阅插件添加订阅时报无权访问

### ISSUE THREAD

**Issue by MobiusT** [zhenxun-org/nonebot_plugins_zhenxun_bot#169]
![image](https://user-images.githubusercontent.com/62053271/217746348-ff2f7a85-7c5e-4ff7-9248-e58a9c54e49c.png)
添加订阅时因为api方法未上送配置的ck，导致api返回API rate limit exceeded

**Comment by yajiwa** [comment]
[35b58e](https://github.com/yajiwa/zhenxun_github_sub/commit/35b58eb15268e3c73bbd36aa2703527951c09f22)，已更新

**Comment by MobiusT** [comment]
感谢
