### ISSUE TITLE
Feat: add `获取MC服务器信息` plugin

### ISSUE THREAD

**Issue by klxf** [zhenxun-org/nonebot_plugins_zhenxun_bot#172]
## 插件名

获取MC服务器信息

## GitHub 地址

[https://github.com/klxf/zhenxun_plugin_getmcserver](https://github.com/klxf/zhenxun_plugin_getmcserver)

## 备注

一个简单的获取服务器在线人数、玩家列表的插件

## 下载地址（可选）

[https://github.com/klxf/zhenxun_plugin_getmcserver/releases](https://github.com/klxf/zhenxun_plugin_getmcserver/releases)

**Comment by Sakuracio** [comment]
Accepted.
