### ISSUE TITLE
七海模型使用时报错

### ISSUE THREAD

**Issue by NumberSir** [zhenxun-org/nonebot_plugins_zhenxun_bot#24]
> 05-11 00:07:39 [ERROR] nonebot | Running matcher <Matcher from Shiruku.plugins.mockingBird, type=message, priority=4, temp=False> failed.
> Traceback (most recent call last):
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\message.py", line 153, in _check_matcher
>     await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)> 
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\message.py", line 202, in _run_matcher
>     await matcher.run(bot, event, state, stack, dependency_cache)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\internal\matcher.py", line 668, in run
>     await self.simple_run(bot, event, state, stack, dependency_cache)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\internal\matcher.py", line 635, in simple_run
>     await handler(
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
>     return await self.call(**values)
>   File "D:\_Joy\Nonebot\Shiruku\Shiruku\plugins\mockingBird\__init__.py", line 125, in _
>     record = await asyncio.get_event_loop().run_in_executor(None, MockingBird.genrator_voice, params)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\MockingBirdOnlyForUse\raw_use.py", line 255, in genrator_voice
>     return cls._synthesize(params)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\MockingBirdOnlyForUse\raw_use.py", line 184, in _synthesize
>     specs = current_synt.synthesize_spectrograms(
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\MockingBirdOnlyForUse\synthesizer\inference.py", line 106, in synthesize_spectrograms
>     self.load()
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\MockingBirdOnlyForUse\synthesizer\inference.py", line 75, in load
>     self._model.load(self.model_fpath, self.device)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\MockingBirdOnlyForUse\synthesizer\models\tacotron.py", line 657, in load
>     self.load_state_dict(checkpoint["model_state"], strict=False)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1482, in load_state_dict
>     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
> RuntimeError: Error(s) in loading state_dict for Tacotron:
> 	size mismatch for gst.stl.attention.W_query.weight: copying a param with shape torch.Size([512, 256]) from checkpoint, the shape in current model is torch.Size([512, 512]).

阿梓模型可以正常使用，`nanami1`模型和`nanami2`模型报这样的错

**Comment by AkashiCoin** [comment]
模型有问题，找个时间删了(
