### ISSUE TITLE
Tarot插件图片发送无法显示

### ISSUE THREAD

**Issue by A1oneR** [zhenxun-org/nonebot_plugins_zhenxun_bot#28]
[CQ:image,file=file:////home/lighthouse/zhenxunbot/plugins/tarot/tarot/星星.jpg]
![FN4U~UJ3X8507`6GZI8DV)G](https://user-images.githubusercontent.com/70164765/169277724-e328ce59-7ca3-4948-8a39-d8d58c060034.png)

**Comment by AkashiCoin** [comment]
请检查该路径下的图片是否存在
