### ISSUE TITLE
加入 avatar 会导致 web UI 无法读取普通插件列表

### ISSUE THREAD

**Issue by BirtyAs** [zhenxun-org/nonebot_plugins_zhenxun_bot#29]
报错内容：
[ERROR] plugins | WEB_UI GET /webui/plugins model：avatar 发生错误 <class 'pydantic.error_wrappers.ValidationError'>：1 validation error for PluginManager
author
  str type expected (type=type_error.str)

感谢dalao 😊❤️

**Comment by BirtyAs** [comment]
暂时改了
__plugin_author__ = ["梦璃雨落","AkashiCoin"]
->
__plugin_author__ = '梦璃雨落,AkashiCoin'

**Comment by AkashiCoin** [comment]
插件已删除，可以使用更全的 头像表情包 插件
