### ISSUE TITLE
read_60缺少模块：ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by enten-forget** [zhenxun-org/nonebot_plugins_zhenxun_bot#33]
https://github.com/zhenxun-org/nonebot_plugins_zhenxun_bot/blob/06e3d8ed5924c619a77e548dc04c1f1d8c09dc23/read_60s/__init__.py#L1

请问大佬们这个是什么包，我在项目下没看到相关的文件，执行pip install requests 也不行

<img width="457" alt="uTools_1653054571353" src="https://user-images.githubusercontent.com/76576302/169542273-f2e2b759-3d8e-4c8a-a768-4f3c71b7a569.png">

**Comment by AkashiCoin** [comment]
请使用pip3 install requests,或者python3 -m pip install requests
