### ISSUE TITLE
枝网查重，vtb查成分等插件的依赖问题

### ISSUE THREAD

**Issue by sxc2588** [zhenxun-org/nonebot_plugins_zhenxun_bot#35]
搭载枝网，查成分插件后会显示缺少nonebot-plugin-htmlrender，bot可以成功启动运行，但插件未安装
![image](https://user-images.githubusercontent.com/105810286/169598760-295a6780-50ea-4fce-aae9-4f7becdc3753.png)
安装那个依赖后，插件成功安装，但启动bot后会出错
![image](https://user-images.githubusercontent.com/105810286/169599299-5b7a27f9-1cc6-4ff5-8000-1d15eff74fe7.png)
![image](https://user-images.githubusercontent.com/105810286/169600759-9f88fdfd-8726-4ccf-a4b4-cdc7dff25633.png)
![image](https://user-images.githubusercontent.com/105810286/169599398-8c9aa4cf-4b5d-4cce-9128-f1ee0df53a49.png)
windows10，请问这种问题怎么处理呢？

**Comment by MingxuanGame** [comment]
see https://github.com/kexue-z/nonebot-plugin-htmlrender/issues/15

**Comment by SPLUS-VABLE** [comment]
请问这个问题解决了吗

**Comment by sxc2588** [comment]
> 这个问题解决了吗？

新版本的bot似乎自动解决了

**Comment by SPLUS-VABLE** [comment]
> > 这个问题解决了吗？
> 
> 新版本的bot似乎自动解决了

我的真寻版本是v0.1.5.6，好像没有解决

**Comment by SPLUS-VABLE** [comment]
> > 这个问题解决了吗？
> 
> 新版本的bot似乎自动解决了

我的真寻版本是v0.1.5.6，好像没有解决
