### ISSUE TITLE
dalao请问搜索的问题

### ISSUE THREAD

**Issue by ayanami648** [zhenxun-org/nonebot_plugins_zhenxun_bot#36]
我吧插件包放进插件文件夹然后重新启动
设置搜索的时候是这样的
![image](https://user-images.githubusercontent.com/105802556/169634703-9f3f2301-de64-4351-bb61-30b76c6c1d0c.png)

**Comment by AkashiCoin** [comment]
字面意思(

**Comment by ayanami648** [comment]
好的大佬 我等等看
