### ISSUE TITLE
mockingbird插件更新后无法朗读日文假名

### ISSUE THREAD

**Issue by ludwigChristi** [zhenxun-org/nonebot_plugins_zhenxun_bot#37]
使用模型为azusa，插件更新后个别中文字符朗读不清晰（更新前无问题），无法朗读日文假名（更新前无此问题）
以下为朗读日文假名时的报错：
![IMG_20220521_235404](https://user-images.githubusercontent.com/48853620/169659976-faeaadb9-7c37-4fc6-96e8-cc8686563a0b.png)

**Comment by AkashiCoin** [comment]
已修复，如果不清晰请设置最大句长为2000
