### ISSUE TITLE
mockingbird运行问题

### ISSUE THREAD

**Issue by luminus-xt** [zhenxun-org/nonebot_plugins_zhenxun_bot#38]
安装后加载成功 但是跑不起来 请问原因可能在哪边呢
![QQ截图20220522102015](https://user-images.githubusercontent.com/106000358/169675570-62250fb6-4a2c-4674-b902-a8f404990a5f.png)

**Comment by AkashiCoin** [comment]
模型并未下载下来，请检查自己的dns解析情况

**Comment by luminus-xt** [comment]
感谢 看日志提示下载成功我就没往这边想

**Comment by dishuii** [comment]
同样的情况 请问解决了吗

**Comment by EE0CFF** [comment]
> 感谢 看日志提示下载成功我就没往这边想

遇到了同样的问题，请问是怎么解决的

**Comment by zhong946555** [comment]
> 感谢 看日志提示下载成功我就没往这边想

请问你是如何解决的呢，我自行从网站下载了模型导入一样无法进行加载

**Comment by luminus-xt** [comment]
> 

我是直接下载了模型导入就解决了

**Comment by zhong946555** [comment]
> > 
> 
> 我是直接下载了模型导入就解决了

可以麻烦您说一下导入的过程吗，我猜可能是我导入有错误

**Comment by luminus-xt** [comment]
> > > 
> > 
> > 
> > 我是直接下载了模型导入就解决了
> 
> 可以麻烦您说一下导入的过程吗，我猜可能是我导入有错误

下载azusa目录和encoder.pt,，g_hifigan.pt 放在bot目录/data/mockingbird文件夹下

**Comment by ayanami648** [comment]
> > > > 
> > > 
> > > 
> > > 我是直接下载了模型导入就解决了
> > 
> > 
> > 可以麻烦您说一下导入的过程吗，我猜可能是我导入有错误
> 
> 下载azusa目录和encoder.pt,，g_hifigan.pt 放在bot目录/data/mockingbird文件夹下

你好请问你是在win环境下进行的安装吗

**Comment by zhong946555** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 我是直接下载了模型导入就解决了
> > > 
> > > 
> > > 可以麻烦您说一下导入的过程吗，我猜可能是我导入有错误
> > 
> > 
> > 下载azusa目录和encoder.pt,，g_hifigan.pt 放在bot目录/data/mockingbird文件夹下
> 
> 你好请问你是在win环境下进行的安装吗

我是centos7环境，我导入的时候只导入了azusa模型目录里的内容，所以报了这个错误，azusa模型目录外部的解码文件也要导进去

**Comment by ayanami648** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > 我是直接下载了模型导入就解决了
> > > > 
> > > > 
> > > > 可以麻烦您说一下导入的过程吗，我猜可能是我导入有错误
> > > 
> > > 
> > > 下载azusa目录和encoder.pt,，g_hifigan.pt 放在bot目录/data/mockingbird文件夹下
> > 
> > 
> > 你好请问你是在win环境下进行的安装吗
> 
> 我是centos7环境，我导入的时候只导入了azusa模型目录里的内容，所以报了这个错误，azusa模型目录外部的解码文件也要导进去

好的感谢 至今我没有找到win安装的方法
