### ISSUE TITLE
你好大佬 装了下面的某个插件搜番功能就挂了 感觉好实用求求帮忙看下

### ISSUE THREAD

**Issue by ayanami648** [zhenxun-org/nonebot_plugins_zhenxun_bot#39]
现在返回的值是这样的
![image](https://user-images.githubusercontent.com/105802556/169697439-9fc7c099-ce51-43ee-bbef-d76080d0bae2.png)
求大佬帮忙看看 是不是某个插件和他冲突了啊 我去卸载

**Comment by ayanami648** [comment]
也有其他人也寄了 哭了 搜番好用呢
![image](https://user-images.githubusercontent.com/105802556/169697665-5d0d0147-a77a-4055-8f27-35c990e8b111.png)

**Comment by AkashiCoin** [comment]
是装了什么插件呢

**Comment by ayanami648** [comment]
大佬我更新真寻了 就正常了 这些插件里肯定有不兼容的 装了碰到运气不好有的功能就寄了
