### ISSUE TITLE
mockingbird插件更新后无法使用nanami模型

### ISSUE THREAD

**Issue by ludwigChristi** [zhenxun-org/nonebot_plugins_zhenxun_bot#41]
将更新前的model_list添加到model_list.json文件后，修改模型为nanami1时提示:  
<class 'RuntimeError'>：Error(s) in loading state_dict for Tacotron:
	size mismatch for gst.stl.attention.W_query.weight: copying a param with shape torch.Size([512, 256]) from checkpoint, the shape in current model is torch.Size([512, 512]).  
  
![Screenshot_20220523_164531_com tencent mobileqq](https://user-images.githubusercontent.com/48853620/169781347-4c5d2308-53f3-4bb5-9386-20cf80ac7b4a.jpg)

**Comment by AkashiCoin** [comment]
小南梅并不适合，此模型已删
