### ISSUE TITLE
mockingbird模型没能下载下来

### ISSUE THREAD

**Issue by WWWA7** [zhenxun-org/nonebot_plugins_zhenxun_bot#43]
和这个 #38 问题一致
![QQ截图20220523201910](https://user-images.githubusercontent.com/84784330/169817737-ebde8393-03ff-451a-91a0-20b0d4b536d9.png)
![image](https://user-images.githubusercontent.com/84784330/169817822-cf8dd8ee-6a77-4700-88af-9949f06342c2.png)
求解

**Comment by WWWA7** [comment]
问题已解决，找到了[模型下载地址](https://pan.yropo.top/home/source/mockingbird/)，下载完成之后放入`\data\mockingbird`文件夹内即可，记得下载这几个后缀为.pt的文件，然后替换原来的文件，最后重启bot即可
![image](https://user-images.githubusercontent.com/84784330/169829173-51cbb259-89aa-4440-bc00-379b0cb58a93.png)
整了一下午的真寻说，可算整好了

**Comment by WWWA7** [comment]
![image](https://user-images.githubusercontent.com/84784330/169936733-7bb18c5d-2a11-4075-942d-186f4256a141.png)
替换完会出现这个问题，可以使用但是不能显示模型也不能切换
解决办法是发送命令：更新模型  即可解决
![%PTW@YF861%V_3VYYF(1I8Q](https://user-images.githubusercontent.com/84784330/169937154-c0d600af-36d6-4268-b98b-633341878927.png)
![image](https://user-images.githubusercontent.com/84784330/169937232-7269c2c2-3d5a-4190-a7ba-2b0bc9fec2dd.png)

**Comment by WWWA7** [comment]
> 

下载替换文件夹内文件和`encoder.pt``g_hifigan.pt``wavernn.pt`这几个文件
比如你需要阿梓语音模型就下载`azusa`文件夹内文件和`encoder.pt``g_hifigan.pt``wavernn.pt`这几个文件，然后全部替换就可以了

**Comment by EE0CFF** [comment]
> 问题已解决，找到了[模型下载地址](https://pan.yropo.top/home/source/mockingbird/)，下载完成之后放入`\data\mockingbird`文件夹内即可，记得下载这几个后缀为.pt的文件，然后替换原来的文件，最后重启bot即可 ![image](https://user-images.githubusercontent.com/84784330/169829173-51cbb259-89aa-4440-bc00-379b0cb58a93.png) 整了一下午的真寻说，可算整好了

啊这，https://pan.yropo.top/source/mockingbird/，这个网挂了，兄弟能不能传一份

**Comment by WWWA7** [comment]
> > 问题已解决，找到了[模型下载地址](https://pan.yropo.top/home/source/mockingbird/)，下载完成之后放入`\data\mockingbird`文件夹内即可，记得下载这几个后缀为.pt的文件，然后替换原来的文件，最后重启bot即可 ![image](https://user-images.githubusercontent.com/84784330/169829173-51cbb259-89aa-4440-bc00-379b0cb58a93.png) 整了一下午的真寻说，可算整好了
> 
> 啊这，[https://pan.yropo.top/source/mockingbird/，这个网挂了，兄弟能不能传一份](https://pan.yropo.top/source/mockingbird/%EF%BC%8C%E8%BF%99%E4%B8%AA%E7%BD%91%E6%8C%82%E4%BA%86%EF%BC%8C%E5%85%84%E5%BC%9F%E8%83%BD%E4%B8%8D%E8%83%BD%E4%BC%A0%E4%B8%80%E4%BB%BD)

好好的啊，我刚试过了，还能进去
不过这里确实下的比较慢，我传个网盘吧，不过我只下了阿梓和天依的两个模型，想要其他的只能自己下了
注意：nanami1里的我没下，文件是0kb
[百度网盘](https://pan.baidu.com/s/1-mmTfcrM4IFAihFfnpmqDA?pwd=lbti)
