### ISSUE TITLE
Arcaea插件无法执行绑定指令，其他指令正常

### ISSUE THREAD

**Issue by Ma1akAs** [zhenxun-org/nonebot_plugins_zhenxun_bot#44]
插件已经成功导入无报错，求大佬指点

05-23 20:46:33 [SUCCESS] nonebot | ONEBOT V11 482713254 | [message.private.friend]: Message -1420001295 from 1763611895 "Arcbind 604301964 yuzoi"
05-23 20:46:33 [INFO] nonebot | Event will be handled by <Matcher from plugins.mute, type=message, priority=1, temp=False>
05-23 20:46:33 [INFO] nonebot | Event will be handled by <Matcher from plugins.black_word, type=message, priority=1, temp=False>
05-23 20:46:33 [INFO] nonebot | Event will be handled by <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False>
05-23 20:46:33 [INFO] nonebot | Matcher <Matcher from plugins.mute, type=message, priority=1, temp=False> running complete
05-23 20:46:33 [INFO] nonebot | Matcher <Matcher from plugins.black_word, type=message, priority=1, temp=False> running complete
05-23 20:46:33 [INFO] nonebot | Matcher <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False> running complete
05-23 20:46:33 [INFO] nonebot | Event will be handled by <Matcher from plugins.ai, type=message, priority=8, temp=False>
05-23 20:46:36 [INFO] plugins | USER 1763611895 GROUP  问题：Arcbind 604301964 yuzoi ---- 回答：无聊！打几 个实用点的字出来聊行不
05-23 20:46:36 [INFO] nonebot | Matcher <Matcher from plugins.ai, type=message, priority=8, temp=False> running complete
05-23 20:46:43 [SUCCESS] nonebot | ONEBOT V11 482713254 | [message.private.friend]: Message -597995673 from 1763611895 "ARCBIND"
05-23 20:46:43 [INFO] nonebot | Event will be handled by <Matcher from plugins.mute, type=message, priority=1, temp=False>
05-23 20:46:43 [INFO] nonebot | Event will be handled by <Matcher from plugins.black_word, type=message, priority=1, temp=False>
05-23 20:46:43 [INFO] nonebot | Event will be handled by <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False>
05-23 20:46:43 [INFO] nonebot | Matcher <Matcher from plugins.mute, type=message, priority=1, temp=False> running complete
05-23 20:46:43 [INFO] nonebot | Matcher <Matcher from plugins.black_word, type=message, priority=1, temp=False> running complete
05-23 20:46:43 [INFO] nonebot | Matcher <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False> running complete
05-23 20:46:43 [INFO] nonebot | Event will be handled by <Matcher from plugins.ai, type=message, priority=8, temp=False>
05-23 20:46:46 [INFO] plugins | USER 1763611895 GROUP  问题：ARCBIND ---- 回答：不知道你发这样的信息是干嘛 的
05-23 20:46:46 [INFO] nonebot | Matcher <Matcher from plugins.ai, type=message, priority=8, temp=False> running complete
05-23 20:47:05 [SUCCESS] nonebot | ONEBOT V11 482713254 | [message.private.friend]: Message 1111481028 from 1763611895 "arcbind 604301964 yuzoi"
05-23 20:47:05 [INFO] nonebot | Event will be handled by <Matcher from plugins.mute, type=message, priority=1, temp=False>
05-23 20:47:05 [INFO] nonebot | Event will be handled by <Matcher from plugins.black_word, type=message, priority=1, temp=False>
05-23 20:47:05 [INFO] nonebot | Event will be handled by <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False>
05-23 20:47:05 [INFO] nonebot | Matcher <Matcher from plugins.mute, type=message, priority=1, temp=False> running complete
05-23 20:47:05 [INFO] nonebot | Matcher <Matcher from plugins.black_word, type=message, priority=1, temp=False> running complete
05-23 20:47:05 [INFO] nonebot | Matcher <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False> running complete
05-23 20:47:05 [INFO] nonebot | Event will be handled by <Matcher from plugins.ai, type=message, priority=8, temp=False>
05-23 20:47:08 [INFO] plugins | USER 1763611895 GROUP  问题：arcbind 604301964 yuzoi ---- 回答：咱是中国人 ，请讲中文，谢谢！
05-23 20:47:08 [INFO] nonebot | Matcher <Matcher from plugins.ai, type=message, priority=8, temp=False> running complete
05-23 20:47:10 [SUCCESS] nonebot | ONEBOT V11 482713254 | [message.private.friend]: Message 892922450 from 1763611895 "arcinfo"
05-23 20:47:10 [INFO] nonebot | Event will be handled by <Matcher from plugins.mute, type=message, priority=1, temp=False>
05-23 20:47:10 [INFO] nonebot | Event will be handled by <Matcher from plugins.black_word, type=message, priority=1, temp=False>
05-23 20:47:10 [INFO] nonebot | Event will be handled by <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False>
05-23 20:47:10 [INFO] nonebot | Matcher <Matcher from plugins.black_word, type=message, priority=1, temp=False> running complete
05-23 20:47:10 [INFO] nonebot | Matcher <Matcher from plugins.mute, type=message, priority=1, temp=False> running complete
05-23 20:47:10 [INFO] nonebot | Matcher <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False> running complete
05-23 20:47:10 [INFO] nonebot | Event will be handled by <Matcher from plugins.Arcaea, type=message, priority=5, temp=False>
05-23 20:47:10 [INFO] nonebot | Matcher <Matcher from plugins.Arcaea, type=message, priority=5, temp=False> running complete
05-23 20:48:00 [SUCCESS] nonebot | ONEBOT V11 482713254 | [message.private.friend]: Message -1406026776 from 1763611895 "/arcbind 604301964 yuzoi"
05-23 20:48:00 [INFO] nonebot | Event will be handled by <Matcher from plugins.mute, type=message, priority=1, temp=False>
05-23 20:48:00 [INFO] nonebot | Event will be handled by <Matcher from plugins.black_word, type=message, priority=1, temp=False>
05-23 20:48:00 [INFO] nonebot | Event will be handled by <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False>
05-23 20:48:00 [INFO] nonebot | Matcher <Matcher from plugins.black_word, type=message, priority=1, temp=False> running complete
05-23 20:48:00 [INFO] nonebot | Matcher <Matcher from plugins.mute, type=message, priority=1, temp=False> running complete
05-23 20:48:00 [INFO] nonebot | Matcher <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False> running complete
05-23 20:48:00 [INFO] nonebot | Event will be handled by <Matcher from plugins.ai, type=message, priority=8, temp=False>
05-23 20:48:03 [INFO] plugins | USER 1763611895 GROUP  问题：/arcbind 604301964 yuzoi ---- 回答：发的什么呀你，乱打的吧
05-23 20:48:03 [INFO] nonebot | Matcher <Matcher from plugins.ai, type=message, priority=8, temp=False> running complete
05-23 20:50:13 [SUCCESS] nonebot | ONEBOT V11 482713254 | [message.private.friend]: Message -617182338 from 1763611895 "arcrc"
05-23 20:50:13 [INFO] nonebot | Event will be handled by <Matcher from plugins.mute, type=message, priority=1, temp=False>
05-23 20:50:13 [INFO] nonebot | Event will be handled by <Matcher from plugins.black_word, type=message, priority=1, temp=False>
05-23 20:50:13 [INFO] nonebot | Event will be handled by <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False>
05-23 20:50:13 [INFO] nonebot | Matcher <Matcher from plugins.black_word, type=message, priority=1, temp=False> running complete
05-23 20:50:13 [INFO] nonebot | Matcher <Matcher from plugins.mute, type=message, priority=1, temp=False> running complete
05-23 20:50:13 [INFO] nonebot | Matcher <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False> running complete
05-23 20:50:13 [INFO] nonebot | Event will be handled by <Matcher from plugins.ai, type=message, priority=8, temp=False>
05-23 20:50:16 [INFO] plugins | USER 1763611895 GROUP  问题：arcrc ---- 回答：不知道你发这样的信息是干嘛的
05-23 20:50:16 [INFO] nonebot | Matcher <Matcher from plugins.ai, type=message, priority=8, temp=False> running complete
05-23 20:50:34 [SUCCESS] nonebot | ONEBOT V11 482713254 | [message.private.friend]: Message 1267308271 from 1763611895 "arcre"
05-23 20:50:34 [INFO] nonebot | Event will be handled by <Matcher from plugins.mute, type=message, priority=1, temp=False>
05-23 20:50:34 [INFO] nonebot | Event will be handled by <Matcher from plugins.black_word, type=message, priority=1, temp=False>
05-23 20:50:34 [INFO] nonebot | Event will be handled by <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False>
05-23 20:50:34 [INFO] nonebot | Matcher <Matcher from plugins.black_word, type=message, priority=1, temp=False> running complete
05-23 20:50:34 [INFO] nonebot | Matcher <Matcher from plugins.mute, type=message, priority=1, temp=False> running complete
05-23 20:50:34 [INFO] nonebot | Matcher <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False> running complete
05-23 20:50:34 [INFO] nonebot | Event will be handled by <Matcher from plugins.Arcaea, type=message, priority=5, temp=False>
05-23 20:50:34 [INFO] nonebot | Matcher <Matcher from plugins.Arcaea, type=message, priority=5, temp=False> running complete
05-23 20:50:39 [SUCCESS] nonebot | ONEBOT V11 482713254 | [message.private.friend]: Message 1015981689 from 1763611895 "arclogin"
05-23 20:50:39 [INFO] nonebot | Event will be handled by <Matcher from plugins.mute, type=message, priority=1, temp=False>
05-23 20:50:39 [INFO] nonebot | Event will be handled by <Matcher from plugins.black_word, type=message, priority=1, temp=False>
05-23 20:50:39 [INFO] nonebot | Event will be handled by <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False>
05-23 20:50:39 [INFO] nonebot | Matcher <Matcher from plugins.mute, type=message, priority=1, temp=False> running complete
05-23 20:50:39 [INFO] nonebot | Matcher <Matcher from plugins.black_word, type=message, priority=1, temp=False> running complete
05-23 20:50:39 [INFO] nonebot | Matcher <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False> running complete
05-23 20:50:39 [INFO] nonebot | Event will be handled by <Matcher from plugins.Arcaea, type=message, priority=5, temp=False>
05-23 20:50:39 [INFO] nonebot | Matcher <Matcher from plugins.Arcaea, type=message, priority=5, temp=False> running complete
05-23 20:50:50 [SUCCESS] nonebot | ONEBOT V11 482713254 | [message.private.friend]: Message 1548300188 from 1763611895 "arcun"
05-23 20:50:50 [INFO] nonebot | Event will be handled by <Matcher from plugins.mute, type=message, priority=1, temp=False>
05-23 20:50:50 [INFO] nonebot | Event will be handled by <Matcher from plugins.black_word, type=message, priority=1, temp=False>
05-23 20:50:50 [INFO] nonebot | Event will be handled by <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False>
05-23 20:50:50 [INFO] nonebot | Matcher <Matcher from plugins.black_word, type=message, priority=1, temp=False> running complete
05-23 20:50:50 [INFO] nonebot | Matcher <Matcher from plugins.mute, type=message, priority=1, temp=False> running complete
05-23 20:50:50 [INFO] nonebot | Matcher <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False> running complete
05-23 20:50:50 [INFO] nonebot | Event will be handled by <Matcher from plugins.Arcaea, type=message, priority=5, temp=False>
05-23 20:50:50 [INFO] nonebot | Matcher <Matcher from plugins.Arcaea, type=message, priority=5, temp=False> running complete
05-23 20:50:55 [SUCCESS] nonebot | ONEBOT V11 482713254 | [message.private.friend]: Message 726540042 from 1763611895 "arcrd 11"
05-23 20:50:55 [INFO] nonebot | Event will be handled by <Matcher from plugins.mute, type=message, priority=1, temp=False>
05-23 20:50:55 [INFO] nonebot | Event will be handled by <Matcher from plugins.black_word, type=message, priority=1, temp=False>
05-23 20:50:55 [INFO] nonebot | Event will be handled by <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False>
05-23 20:50:55 [INFO] nonebot | Matcher <Matcher from plugins.mute, type=message, priority=1, temp=False> running complete
05-23 20:50:55 [INFO] nonebot | Matcher <Matcher from plugins.black_word, type=message, priority=1, temp=False> running complete
05-23 20:50:55 [INFO] nonebot | Matcher <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False> running complete
05-23 20:50:55 [INFO] nonebot | Event will be handled by <Matcher from plugins.Arcaea, type=message, priority=5, temp=False>
05-23 20:50:55 [INFO] nonebot | Matcher <Matcher from plugins.Arcaea, type=message, priority=5, temp=False> running complete

**Comment by Darphas** [comment]
私聊绑定不了，要在群里绑定，顺便问一下使用arcinfo指令看不了b30怎么解决

**Comment by AkashiCoin** [comment]
请问绑定查分账号了吗，需要绑定一个账号用于查分

**Comment by Darphas** [comment]
arclogin和arcbind都有绑定，输入arcinfo反馈的是正在查询，请耐心等待，控制台反馈的是Start Arcaea API，之后就没动静了

**Comment by AkashiCoin** [comment]
> arclogin和arcbind都有绑定，输入arcinfo反馈的是正在查询，请耐心等待，控制台反馈的是Start Arcaea API，之后就没动静了

est查分速度比较慢，请等待
