### ISSUE TITLE
需要的依赖已经安装，但还是报错

### ISSUE THREAD

**Issue by ayachimako** [zhenxun-org/nonebot_plugins_zhenxun_bot#45]
如图
![图片](https://user-images.githubusercontent.com/105858150/169823932-82a1e76a-135b-4dee-ba8b-7dc7657a1fe5.png)
报错的依赖有emoji,jinja2,pinyin,arrow,thefuzz,aiocache,imageio
这些都是安装过了的
![图片](https://user-images.githubusercontent.com/105858150/169824427-c294b99e-aa48-4afa-8b5b-d1a4cf360c73.png)
![图片](https://user-images.githubusercontent.com/105858150/169824506-37a86212-410f-4ec1-9945-b5b7f3a86c6c.png)
![图片](https://user-images.githubusercontent.com/105858150/169824594-63779c6a-3726-4b0e-8945-3dba83197b6a.png)
![图片](https://user-images.githubusercontent.com/105858150/169824659-288440a3-47ed-4967-b9e3-4107d5362e31.png)
好像需要依赖的插件都报错了.........求解

**Comment by WWWA7** [comment]
再装一遍试试，记得在虚拟环境中装

**Comment by ayachimako** [comment]
> 再装一遍试试，记得在虚拟环境中装

已经卸载过一次然后安装了，操作系统是Ubuntu22.04

**Comment by ayachimako** [comment]
安装成功了，在zhenxun_bot目录里打开终端使用poetry add命令添加依赖就可以了
但现在机器人只会回复命令，ai插件的功能没有了咋整，看日志也没有异常或者报错

**Comment by ayachimako** [comment]
问题解决了 ，下载插件仓库如果缺少依赖报错一定要一个个解决掉！或者删掉不需要的插件也可以
