### ISSUE TITLE
在线运行代码插件出现bug

### ISSUE THREAD

**Issue by ZTSakuya** [zhenxun-org/nonebot_plugins_zhenxun_bot#49]
在线运行代码读取输入数据出现问题

**Comment by ZTSakuya** [comment]
![image](https://user-images.githubusercontent.com/88840705/169951538-09820d05-bf32-4e49-8dc5-f7ba8f4d2613.png)

**Comment by ZTSakuya** [comment]
将data_source.py中"stdin":stdin
![image](https://user-images.githubusercontent.com/88840705/169951606-9a1acb8b-1df7-408b-94eb-ea5bfb12c1f6.png)
修改为
![image](https://user-images.githubusercontent.com/88840705/169951670-cf61643c-4391-4540-9df9-ab6e41c9289d.png)
"stdin":a[2]后可以解决问题

**Comment by ZTSakuya** [comment]
我不清楚会不会导致其他bug（

**Comment by AkashiCoin** [comment]
可以的话，可以在 [MingxuanGame/zhenxun_plugin_code](https://github.com/MingxuanGame/zhenxun_plugin_code) 提出你的issue，这个插件这边只存在一个索引

**Comment by ZTSakuya** [comment]
> 可以的话，可以在 [MingxuanGame/zhenxun_plugin_code](https://github.com/MingxuanGame/zhenxun_plugin_code) 提出你的issue，这个插件这边只存在一个索引

好的好的
