### ISSUE TITLE
大佬关于monckingbird安装 无法载入

### ISSUE THREAD

**Issue by ayanami648** [zhenxun-org/nonebot_plugins_zhenxun_bot#50]
安装的时候报错是这样的
![image](https://user-images.githubusercontent.com/105802556/170032842-cd090089-7c3d-4352-8c4a-a059362fed25.png)
![image](https://user-images.githubusercontent.com/105802556/170032905-4ddbd735-0402-4bca-aef9-3e024f81173a.png)

安依赖是这样的
![image](https://user-images.githubusercontent.com/105802556/170033336-4e8e1d57-3ff1-4bae-858c-91d86582c10b.png)
最后bot运行这样
![image](https://user-images.githubusercontent.com/105802556/170033596-6de56961-3a29-45e8-ba7b-ee126d34730e.png)
求解大佬哪里有误

**Comment by AkashiCoin** [comment]
使用pip install mockingbirdforuse前请安装python3-dev，例如使用apt install python3-dev

**Comment by eachbol2333** [comment]
请问我安装mockingbirdforuse时一直安装不上webrtcvad，我也安装了c++14，谷歌半天也找不出个所以然，求助
![image](https://user-images.githubusercontent.com/105063888/170051267-28ee9cc7-2b60-4d0c-be47-138c95549c4a.png)

**Comment by AkashiCoin** [comment]
> 请问我安装mockingbirdforuse时一直安装不上webrtcvad，我也安装了c++14，谷歌半天也找不出个所以然，求助 ![image](https://user-images.githubusercontent.com/105063888/170051267-28ee9cc7-2b60-4d0c-be47-138c95549c4a.png)

请参考我上一条评论

**Comment by ayachimako** [comment]
> 使用pip install mockingbirdforuse前请安装python3-dev，例如使用apt install python3-dev

想问一下大佬，我是已经安装了python3-dev，也安装了mockingbirdforuse，但还是显示No module named 'mockingbirdforuse'
![图片](https://user-images.githubusercontent.com/105858150/170057890-c8d495e7-1eb1-4b82-9450-cfaecbb07a59.png)
这边是第二次pip install提示已安装
![图片](https://user-images.githubusercontent.com/105858150/170058022-491d16b9-5bd2-4854-940d-99f6487b9795.png)
然后这是报错信息
![图片](https://user-images.githubusercontent.com/105858150/170058232-55c8852e-5c1a-462d-8ef9-169e8df76c30.png)
![图片](https://user-images.githubusercontent.com/105858150/170058275-cbf6fef8-6cf3-49f8-aa8e-ad8fec13ea09.png)

**Comment by ayachimako** [comment]
> > > 使用pip install mockingbirdforuse前请安装python3-dev，例如使用apt install python3-dev
> > 
> > 
> > 想问一下大佬，我是已经安装了python3-dev，也安装了mockingbirdforuse，但还是显示No module named 'mockingbirdforuse' ![图片](https://user-images.githubusercontent.com/105858150/170057890-c8d495e7-1eb1-4b82-9450-cfaecbb07a59.png) 这边是第二次pip install提示已安装 ![图片](https://user-images.githubusercontent.com/105858150/170058022-491d16b9-5bd2-4854-940d-99f6487b9795.png) 然后这是报错信息 ![图片](https://user-images.githubusercontent.com/105858150/170058232-55c8852e-5c1a-462d-8ef9-169e8df76c30.png) ![图片](https://user-images.githubusercontent.com/105858150/170058275-cbf6fef8-6cf3-49f8-aa8e-ad8fec13ea09.png)
> 
> 虚拟环境中安装

![图片](https://user-images.githubusercontent.com/105858150/170066819-2b2584bd-2b2f-4e7a-b4dc-f6fddf8dfc86.png)
按大佬说的安装了但还是这样

**Comment by ayanami648** [comment]
> 

你好大佬请问win下如何去安装dev呢 apt命令好像是用于Linux

**Comment by AkashiCoin** [comment]
> > 
> 
> 你好大佬请问win下如何去安装dev呢 apt命令好像是用于Linux

win下应该不会有这个错误，如果你有问题请提交issue并附上报错日志

**Comment by AkashiCoin** [comment]
> > > > 
> > > 
> > > 
> > > 你好大佬请问win下如何去安装dev呢 apt命令好像是用于Linux
> > 
> > 
> > win下应该不会有这个错误，如果你有问题请提交issue并附上报错日志
> 
> 不好意思大佬我比较小白，请看 ![image](https://user-images.githubusercontent.com/105802556/170071247-62c95f03-e67b-4e7b-83c2-61cc1db84465.png)

请另提issue
