### ISSUE TITLE
Github 插件安装后无法使用AI功能 删除后功能正常

### ISSUE THREAD

**Issue by BirtyAs** [zhenxun-org/nonebot_plugins_zhenxun_bot#58]
日志：
05-25 17:38:03 [SUCCESS] nonebot | ONEBOT V11 2753892559 | [message.private.friend]: Message 1848901318 from xxxxxxxx "你好呀"
05-25 17:38:03 [INFO] nonebot | Event will be handled by <Matcher from plugins.mute, type=message, priority=1, temp=False>
05-25 17:38:03 [INFO] nonebot | Event will be handled by <Matcher from plugins.black_word, type=message, priority=1, temp=False>
05-25 17:38:03 [INFO] nonebot | Event will be handled by <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False>
05-25 17:38:03 [INFO] nonebot | Matcher <Matcher from plugins.mute, type=message, priority=1, temp=False> running complete
05-25 17:38:03 [INFO] nonebot | Matcher <Matcher from plugins.black_word, type=message, priority=1, temp=False> running complete
05-25 17:38:03 [INFO] nonebot | Matcher <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False> running complete
05-25 17:38:03 [INFO] nonebot | Event will be handled by <Matcher from plugins.github, type=message, priority=5, temp=False>
05-25 17:38:03 [INFO] nonebot | Matcher <Matcher from plugins.github, type=message, priority=5, temp=False> running complete
^C05-25 17:38:19 [INFO] uvicorn | Shutting down

**Comment by ayachimako** [comment]
同类型问题询问
系统版本Ubuntu22.04
真寻版本0.1.5.6
错误截图
![图片](https://user-images.githubusercontent.com/105858150/170294751-5a6116ae-1664-4b90-a964-45dfad6f3ff1.png)
![图片](https://user-images.githubusercontent.com/105858150/170294822-52ced971-da51-4bac-b0e0-ccc0dacbb1aa.png)
错误说明：
更新真寻到0.1.5.6后无法使用bt插件，在上一版本安装插件仓库里的插件后还能使用，应该是与哪个插件冲突了
ai插件已通过删除GitHub插件恢复，但还不知道截胡bt插件的是哪个

**Comment by SinKy-Yan** [comment]
我也遇到相同问题，github订阅插件把消息event拦截了导致ai插件收不到消息，等待修复
