### ISSUE TITLE
ELF_RSS报错 name 'rss_list' is not defined

### ISSUE THREAD

**Issue by dishuii** [zhenxun-org/nonebot_plugins_zhenxun_bot#68]
依赖都安装成功了，无报错，但是启动机器人提示如下报错，请教一下如何解决，谢谢
![Snipaste_2022-05-27_14-06-56](https://user-images.githubusercontent.com/33979662/170641985-c250842e-d43d-412a-be39-70b67f7a59b1.jpg)
![Snipaste_2022-05-27_14-09-31](https://user-images.githubusercontent.com/33979662/170642047-9651b58e-ae41-4784-aa95-e0fb2d1b9ce7.jpg)

**Comment by BlackLotus-AL** [comment]
同问，我也遇到了一样的报错

**Comment by 1294266616** [comment]
看起来是移植的时候少了些东西
rss_list = Rss.read_rss()  # 读取list
    if not rss_list:
        await bot.send_private_msg(
            user_id=int(list(config.superusers)[0]),
            message=f"第一次启动，你还没有订阅，记得添加哟！\n{boot_message}",
        )
        logger.info("第一次启动，你还没有订阅，记得添加哟！")
在原来的项目上找到了
