### ISSUE TITLE
apex的插件出错

### ISSUE THREAD

**Issue by Natsumelan** [zhenxun-org/nonebot_plugins_zhenxun_bot#69]
![image](https://user-images.githubusercontent.com/105765802/170708286-7312ae21-7e84-4ae4-b2b9-23254a791302.png)
请问这是怎么回事

**Comment by SinKy-Yan** [comment]
@Josef1999
还有 https://github.com/zhenxun-org/nonebot_plugins_zhenxun_bot/issues/64 也提及这个问题了，能看一下怎么回事吗

**Comment by Josef1999** [comment]
这个是因为先前的config.json中指向qq_eaID.json的路径末尾有多余的斜杠"\"，这个问题已经修复了，下载最新版的插件就行

**Comment by a930389426** [comment]
> 

我下载了，但还是同样出现了这个问题

**Comment by Josef1999** [comment]
可以提供你config.json文件的截图吗

**Comment by dongbao666666** [comment]
> 这个问题怎么搞
![QQ图片20220530205908](https://user-images.githubusercontent.com/95880227/170997643-75dbf038-5821-4e16-8c80-fbd925cdd1af.png)

**Comment by a930389426** [comment]
![QQ截图20220531133529](https://user-images.githubusercontent.com/59648220/171100468-06479f70-515a-40d1-a584-cf41743ab3f4.png)
@Josef1999
