### ISSUE TITLE
ddchek插件安装显示ModuleNotFoundError: No module named 'nonebot_plugin_htmlrender'

### ISSUE THREAD

**Issue by SPLUS-VABLE** [zhenxun-org/nonebot_plugins_zhenxun_bot#70]
![image](https://user-images.githubusercontent.com/42440354/170807131-5ca11f35-687c-4fdf-8815-8e13ffa1ff87.png)

**Comment by Natsumelan** [comment]
用pip下载nonebot_plugin_htmlrender试试

**Comment by SPLUS-VABLE** [comment]
> 用pip下载nonebot_plugin_htmlrender试试

试过了，pip install nonebot_plugin_htmlrender，项目启动直接报错，把这个依赖卸载之后又能够重新启动，不知道是怎么回事。

**Comment by po-lan** [comment]
> > 用pip下载nonebot_plugin_htmlrender试试
> 
> 试过了，pip install nonebot_plugin_htmlrender，项目启动直接报错，把这个依赖卸载之后又能够重新启动，不知道是怎么回事。

Windows版本无法安装那个插件的一个依赖，我有个改版是适配Windows的，过一阵会分享出来，

**Comment by SPLUS-VABLE** [comment]
> > > 用pip下载nonebot_plugin_htmlrender试试
> > 
> > 
> > 试过了，pip install nonebot_plugin_htmlrender，项目启动直接报错，把这个依赖卸载之后又能够重新启动，不知道是怎么回事。
> 
> Windows版本无法安装那个插件的一个依赖，我有个改版是适配Windows的，过一阵会分享出来，

好的谢谢大佬！

**Comment by po-lan** [comment]
> > > > 用pip下载nonebot_plugin_htmlrender试试
> > > 
> > > 
> > > 试过了，pip install nonebot_plugin_htmlrender，项目启动直接报错，把这个依赖卸载之后又能够重新启动，不知道是怎么回事。
> > 
> > 
> > Windows版本无法安装那个插件的一个依赖，我有个改版是适配Windows的，过一阵会分享出来，
> 
> 好的谢谢大佬！

如果可以的话 把这个 ituss关了吧

**Comment by po-lan** [comment]
我目前在测试新的版本
抄了部分的htmlrender的代码，我通过命令行是可以正常使用的
