### ISSUE TITLE
关于ddcheck报错问题

### ISSUE THREAD

**Issue by fenglingmingxue** [zhenxun-org/nonebot_plugins_zhenxun_bot#79]
![Q6%$R`4~TLD1RB46`WS6_{1](https://user-images.githubusercontent.com/100131245/171534456-9e7b31e5-4e65-4932-a873-96aa6e9faf4c.png)
不明白问题出在哪里。

**Comment by ayakasuki** [comment]
+1,我也是报mid

**Comment by chara1051** [comment]
一样的

**Comment by OiCkilL** [comment]
<img width="903" alt="image" src="https://user-images.githubusercontent.com/613988/172313587-0e60a3b1-6d83-4d4c-ac15-4fcdfeb4259c.png">
我这边报的这个，好像也类似

**Comment by dick0841** [comment]
![image](https://user-images.githubusercontent.com/50237543/174491645-9227f8f4-bd8d-4b5d-add0-76fa5e23a78e.png)
我报的math,,
