### ISSUE TITLE
Apex查询工具(图片版)的api申请网站挂了吗

### ISSUE THREAD

**Issue by dishuii** [zhenxun-org/nonebot_plugins_zhenxun_bot#82]
https://portal.apexlegendsapi.com/
点申请没反应了

**Comment by AreCie** [comment]
> https://portal.apexlegendsapi.com/ 点申请没反应了

![image](https://user-images.githubusercontent.com/41849402/171827296-559c1876-e07b-40ea-82e2-988fb45eaa10.png)
没有，一切正常

**Comment by dishuii** [comment]
网站用的jsdelivr挂了，开全局打开网站就好了
