### ISSUE TITLE
Feat: add `原神角色卡片` plugin

### ISSUE THREAD

**Issue by CRAZYShimakaze** [zhenxun-org/nonebot_plugins_zhenxun_bot#83]
## 插件名

原神角色卡片

## GitHub 地址

[原神角色卡片](https://github.com/CRAZYShimakaze/zhenxun_plugin_genshin_role_card)

## 备注

参考自[zhenxun-plugin-almanac](https://github.com/zhenxun-org/zhenxun_bot-tg/tree/main/plugins/genshin/almanac)

展示橱窗中第一个角色的面板数据

**Comment by MingxuanGame** [comment]
已添加
