### ISSUE TITLE
Feat: add `Intercept_Withdraw` plugin

### ISSUE THREAD

**Issue by HDU-Nbsp** [zhenxun-org/nonebot_plugins_zhenxun_bot#87]
## 插件名

群消息防撤回/闪照捕获

## GitHub 地址

<https://github.com/HDU-Nbsp/zhenxun_plugin_intercept_withdraw.git>

## 备注

自动监听群内消息，将撤回消息与闪照（解析为图片后）反馈给超级用户

**Comment by Sakuracio** [comment]
Accepted.
