### ISSUE TITLE
Feat: add `zhenxun_plugin_weibo` plugin

### ISSUE THREAD

**Issue by LambdaYH** [zhenxun-org/nonebot_plugins_zhenxun_bot#88]
## 插件名

微博推送

## GitHub 地址

https://github.com/LambdaYH/zhenxun_plugin_weibo

## 备注

移植自[KokkoroBot-Multi-Platform](https://github.com/zzbslayer/KokkoroBot-Multi-Platform)，在群聊内推送特定的微博（可配置）

**Comment by Sakuracio** [comment]
Accepted
