### ISSUE TITLE
小白，不会安装插件，安装运行时报错。

### ISSUE THREAD

**Issue by waq527** [zhenxun-org/nonebot_plugins_zhenxun_bot#93]
![720aa481d8e2c60e](https://user-images.githubusercontent.com/106297247/173833195-0f79b7b6-ecab-4888-b671-acbaa3bca676.png)
小白想请假一下这个是这么回事

**Comment by Nekomik** [comment]
缺少模块，pip install imageio

**Comment by waq527** [comment]
感谢解决了
