### ISSUE TITLE
[Q]: 请问该项目 index 分支的 `zhenxun_plugins.json` 文件与 master 分支的关系

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [zhenxun-org/nonebot_plugins_zhenxun_bot#96]
请问该项目 index 分支的 `zhenxun_plugins.json` 文件与 master 分支的关系是什么呀❓
1.  请问 `zhenxun_plugins.json` 文件列出的插件可以使用插件管理器进行管理, 还是 master 分支的插件可以使用插件管理器进行管理, 抑或两者均可使用插件管理器进行管理❓
2. 请问开发者进行贡献时除了更新 index 分支的 README.md 文件, 还需要更新 `zhenxun_plugins.json` 文件或 master 分支嘛, 抑或两者均需要更新❓

**Comment by yajiwa** [comment]
master分支是之前插件不多的时候把所有插件文件都塞里面了，后来发现太乱了创建了index当索引，然后如果一直往master塞插件会导致仓库文件又多又乱，所以后来就变成只接收仓库地址改 README.md 就可以了。
只有`zhenxun_plugins.json`文件列出的插件可以用真寻的插件商店进行管理，因为里面有下载地址，很多插件没发版没有压缩包，所以不能放进去
